---
title: "Week 2 Journal"
date: "2024-06-24"
categories: ["June", "Journal"]
---

# Week 2 Journal

The second week began with a briefing on my new task: creating a dashboard from a dataset of food saved by the community fridge. This required data analysis and visualisation to highlight the fridge's impact on reducing food waste. I created a GitHub repository for managing the Food Waste Data and used RStudio for the first time to perform initial data analysis and visualisations. This allowed me to apply my data analysis skills and learn new R techniques, with the visualisations of the data forming the dashboard's foundation.

I planned the dashboard's structure, selecting key metrics and deciding on the best display methods to convey the information effectively. Drafting the dashboard in RStudio involved experimenting with different layouts to ensure it was informative and visually appealing. Towards the end of the week, we had a checkup meeting with my employer and university supervisors to discuss progress and gather feedback, ensuring everyone was informed on the project's objectives and timeline. Overall, this week focused on getting to grips with using R and laying the groundwork for a functional and informative dashboard through data analysis and initial design drafts.