---
title: "Week 1 Journal"
date: "2024-07-15"
categories: ["Week 1", "Journal"]
---

# Week 1 Journal

The first week predominantly focused on getting acquainted with my colleagues and having an initial meeting to assign my first project. This initial project was centred around a communal food fridge aimed at saving food waste from local supermarkets through donations. My task was to create a Python script that could process a series of images, automatically collected by a setup camera, into a time-lapse video, allowing viewers to see how the food was interacted with over time.

This project was a great opportunity to apply my coding skills to develop this Python script. I also learned new skills, such as creating a QR code using Python that linked to the community fridge website, which was a practical implementation of the programming knowledge I gained during my coursework. Setting up a GitHub repository and creating a comprehensive README file helped me understand the importance of documentation and version control in real-world projects. Using DaVinci Resolve to edit the video was also a new experience that enhanced my multimedia skills. Additionally, planning the video content and structure required creativity and project management. Overall, this week blended technical and soft skills development, laying a solid foundation for the tasks ahead.