---
title: "Week 2 Journal"
date-format: iso
date: "2024-06-24"
categories: []
---

[Dashboard progress 1](https://haucommunityfridge.github.io/James_FoodWasteData/FoodWasteDataDashboard.html)
```{python}
```
[HAU Community Fridge GitHub Repo](https://github.com/HAUCommunityFridge/James_FoodWasteData/tree/James-branch?tab=readme-ov-file)

This week began with a briefing on a new task: conducting data analysis on a dataset of food saved by the community fridge and creating a dashboard highlighting the fridge's impact on reducing food waste. I created a GitHub repository to manage the Food Waste Data, ensuring that all project files were organised and accessible.

I used RStudio for the first time for data analysis and visualisation, which allowed me to apply my existing data analysis skills while also learning new techniques in R. The visualisations generated during this process formed the foundation of the dashboard I was tasked with creating.

I planned the structure of the dashboard, selecting key metrics and choosing the best display methods to ensure information was conveyed clearly to viewers. Drafting the dashboard in RStudio using Quarto involved experimenting with different layouts and designs to balance informativeness and visual appeal.

Towards the end of the week, we held a check-up meeting with the employer and university supervisors to discuss my progress. This meeting helped align our goals, gather feedback, and ensure everyone was informed about the project's objectives and timeline. Overall, this week centred on learning R and laying the groundwork for a functional and informative dashboard.
