---
title: "Week 7 Journal"
date: "2024-07-29"
date-format: iso
categories: []
---

[My BirdNET GitHub Repo](https://github.com/Jamess200/MyBirdNetTest)
```{python}
```

This week, I focused on data management, coding, and project organisation tasks. I received new data for the FoodBank project and began drafting a solutions report focused on cleaning and restructuring the current untidy Excel dataset to enhance its usability. I then concentrated on preprocessing and cleaning this dataset, setting the foundation for an updated dashboard.

To ensure the steps were reproducible, I used Google Colab and made a new repository in GitHub to upload the dashboard, cleaned data, and report. I also removed redundant notebooks from some of my Bird Net repository while consolidating the essential ones into a primary notebook and organising documentation-related files into a dedicated folder. I also developed an R program to retrieve area-specific data from the Global Biodiversity Information Facility (GBIF) around Harper Adams University. I explored automating the conversion of human detections into a data file and submitted a request for eBird data to use in the Bird Net project to finish the confusion Matrix from the previous week.
