---
title: "Week 4 Journal"
date: "2024-07-08"
date-format: iso
categories: []
---

[My BirdNET GitHub Repo](https://github.com/Jamess200/MyBirdNetTest)
```{python}
```

This week, I began exploring Bird Net and familiarising myself with its libraries and the format of its output data using Google Colab to test the machine-learning framework. I referred to the official Bird NET GitHub page to understand its functionalities better. I also received the first batch of audio recordings to analyse and wrote a script in Google Colab to test run times, interpreting how long it would take to process the audio files. I updated the code to create box plots for run times across various files, which were run three times each to compare how run times differed with multiple runs of the same file. I carried out an ANOVA to determine if there was a significant difference in the time Bird Net took to analyse the audio files. The results showed no significant difference in the run times between different files, with a p-value of 0.80.

I consolidated all CSV data from all transects into one CSV file, ensuring the correct format and columns. Finally, I tested making graphs with the new CSV data. This week was productive in understanding Bird Net's processing times and data analysis capabilities and using Google Colab to create understandable and reproducible code that others can read and run from my GitHub repository.