---
title: "Week 5 Journal"
date: "2024-07-15"
date-format: iso
categories: []
---

[My BirdNET GitHub Repo](https://github.com/Jamess200/MyBirdNetTest)
```{python}
```

This week, I focused on several tasks to enhance the analysis of bird species predictions and improve the accuracy of detections. I created a diagnostic histogram to visualise the distribution of confidence scores for all bird species predictions, highlighting the overall accuracy of the detection model and identifying areas needing improvement. Additionally, I analysed the top and bottom three bird species observed more than 20 times to determine if common birds have higher detection accuracy than rarer ones. I calculated the average confidence score for each species and performed ANOVA and Pearson correlation analyses to explore the relationship between detection frequency and confidence scores.

In addition, I converted my weekly blog notes into a more accessible format using Quarto in RStudio, which will be uploaded to GitHub Pages. I attended weekly meetings and conferences to network and learn about new developments. I investigated the likelihood of rare bird detections being false positives by analysing confidence scores and recommended an accuracy cut-off of 0.5-0.6 to reduce false positives. I compiled a two-page report summarising my findings and recommendations. Finally, I calculated the average species richness, finding approximately 72 unique species per day, indicating good biodiversity. I suggested consistent measurement over time to better assess biodiversity trends.