---
title: "Week 7 Journal"
date: "2024-07-29"
date-format: iso
categories: []
---

[My BirdNET GitHub Repo](https://github.com/Jamess200/MyBirdNetTest)
```{python}
```

This week, I focused on several tasks related to the Bird Net project. I created a README file and added Google Colab links to improve the project's usability and documentation. Additionally, I attempted to calculate the total number of detections by counting up each 3-second segment to identify how many detections were excluded due to confidence cut-offs. However, this proved challenging as multiple detections were often recorded within a single 3-second segment, complicating accurate calculations.

Using a confusion matrix, I also began drafting a comparison between AI predictions and human observations. This involved counting true positives, false positives, and false negatives. To begin completing the confusion matrix, I started exploring the Global Biodiversity Information Facility (GBIF) as a potential source to obtain the true negatives. I then experimented with different confidence cut-offs for the AI predictions, finding that higher confidence thresholds led to fewer false positives and reduced the number of true positives. Meanwhile, lower confidence cut-offs led to the opposite, with more false positives and true positives. This highlighted the trade-off between precision and recall.
