---
title: "Week 3 Journal"
date: "2024-07-01"
date-format: iso
categories: []
---

[Dashboard progress 2](https://haucommunityfridge.github.io/James_FoodWasteData/FoodWasteDataDashboard.html)
```{python}
```
[HAU Community Fridge GitHub Repo](https://github.com/HAUCommunityFridge/James_FoodWasteData/tree/James-branch?tab=readme-ov-file)


This week, focused on finalising the dashboard for the community fridge project by adding an "About" section and integrating a QR code linking to the community fridge website, enhancing the dashboard's accessibility and user engagement. I carefully selected and implemented visualisations to display information, such as the total number of food items saved, daily averages, and the distribution of food categories. These enhancements ensured that the dashboard communicated the impact of the community fridge to viewers.

Once the visualisations were completed, I finalised the dashboard and ensured it was polished and ready for use. I also created a comprehensive README file for the dashboard repository using Markdown. This documentation ensured that others could easily understand and maintain the dashboard in the future.

Towards the end of the week, I had an introductory meeting about the main project, Bird Net, an open-source machine-learning framework designed to analyse audio recordings and identify bird species based on their calls. This discussion provided an overview of the project and set the stage for upcoming tasks, such as preparing and analysing audio data to support conservation efforts.

Overall, this week marked the successful completion of the dashboard and laid the groundwork for the future Bird Net project. The transition from one project to another highlighted the importance of adaptability and continuous learning in a professional environment.
