---
title: "Week 1 Journal"
date: "2024-06-17"
date-format: iso
categories: []
---

[Food Bank Video Creator GitHub Repo](https://github.com/Jamess200/FoodBank)
```{python}
```
[Time Lapse Video](https://youtu.be/YQYi-I0GTlc)

The first week of my placement focused on getting acquainted with my colleagues and attending a meeting to discuss an initial smaller project to test my knowledge and skills. This project was centred around a communal food fridge initiative to reduce food waste by collecting donations from local supermarkets. My main task for this project was to develop a Python script to process a series of images, automatically captured by a setup camera, into a time-lapse video. This video would allow viewers to observe how the food in the fridge was interacted with over time.

In addition to the image processing task, I also created a QR code using Python, which linked to the community fridge's website. This task provided a practical application of the programming knowledge I had acquired during my coursework. Furthermore, I set up a GitHub repository for the project, where I created a README file. This experience with GitHub was a first and deepened my understanding of the importance of documentation and version control in real-world projects.

I also learned to use DaVinci Resolve to edit the time-lapse video, a new experience that helped enhance my multimedia skills. Additionally, planning the content and structure of the video required creativity and project management.
Overall, this first week allowed me to apply technical and soft skills in a real-world context, laying a foundation for the tasks and challenges I would encounter in the following weeks.
